### ISSUE TITLE
Danish synonym augmentation return english suggestions

### ISSUE THREAD

**Issue by martincjespersen** [KennethEnevoldsen/augmenty#29] opened 2021-08-09 09:19 UTC
**Code:**
```
import spacy
import augmenty
nlp = spacy.load("da_core_news_sm")
danish_synonym_augmenter = augmenty.load("wordnet_synonym.v1", level=1, lang="da")

texts = ["Hej, jeg hedder Person 1 og er fra Lokation 1 og arbejder i Organisation 1, mit cpr er CPR 1, telefon: Telefon 5 og email: Email 1. Person 1 er en 20 årig mand. Person 2 er en person som arbejder i Organisation 2. Person 3 er en mand som bor i Lokation 1 og arbejder i Organisation 4"]

augmented_texts = augmenty.texts(texts, augmenter=danish_synonym_augmenter, nlp=nlp)
for text in augmented_texts:
    diff = [ (x,y) for x,y in zip(text.split(), texts[0].split()) if x != y ]
    print(diff)
```

**Output:**
```
[('federation', 'Organisation'), ('telephone:', 'telefon:'), ('telephone_set', 'Telefon'), ('person', 'Person'), ('adult_male.', 'mand.'), ('individual', 'Person'), ('somebody', 'person'), ('confederation', 'Organisation'), ('man', 'Person'), ('adult_male', 'mand'), ('confederation', 'Organisation')]
```

**Environment information**
* augmenty Version Used: 0.0.3 
* Operating System: Mac OS / Windows
* Python Version Used: 3.6.5 & 3.9.5
* spaCy Version Used: spacy==3.1.1
* NLTK Version Used: nltk==3.6.2
* Environment Information: conda environment

**Comment by KennethEnevoldsen** [comment] 2021-08-10 11:33
The problem is now fixed. The issue was that the language wasn't specified when generating the lemmas.

Now when running:
```
import spacy
import augmenty
nlp = spacy.load("da_core_news_sm")
danish_synonym_augmenter = augmenty.load("wordnet_synonym.v1", level=1, lang="da")

texts = ["Hej, jeg hedder Person 1 og er fra Lokation 1 og arbejder i Organisation 1, mit cpr er CPR 1, telefon: Telefon 5 og email: Email 1. Person 1 er en 20 årig mand. Person 2 er en person som arbejder i Organisation 2. Person 3 er en mand som bor i Lokation 1 og arbejder i Organisation 4"]

augmented_texts = list(augmenty.texts(texts, augmenter=danish_synonym_augmenter, nlp=nlp))
augmented_texts
```

You should get:
```
["Hej, jeg hedder Person 1 og er fra Lokation 1 og arbejder i organisation 1, mit cpr er CPR 1, knogle: telefon 5 og email: Email 1. mand 1 er en 20 årig herre. person 2 er en m/k'er som arbejder i organisation 2. menneske 3 er en mand som bor i Lokation 1 og arbejder i organisation 4"]
```

Which seems reasonable, albeit the casing is neglected. Which I also fixed so you will actually get:

```
["Hej, jeg hedder Person 1 og er fra Lokation 1 og arbejder i Organisation 1, mit cpr er CPR 1, telefon: Knogle 5 og email: Email 1. Mand 1 er en 20 årig mand. M/k'er 2 er en person som arbejder i Forbund 2. Hoved 3 er en mand som bor i Lokation 1 og arbejder i Organisation 4"]
```

Although you could set `keep_titlecase=False` if you prefer the first case.

**Closed by KennethEnevoldsen** 2021-08-10 11:33 UTC
Labels: bug
